TechCommerce/Models/Cart.cs
namespace TechCommerce.Models
{
    public class Cart
    {
        public int Id { get; set; }
        public decimal totalPrice { get; set; }

        public ICollection<CartProducts> CaPr { get; set; } = new HashSet<CartProducts>();
        public Customer Customer { get; set; }
    }
}

TechCommerce/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TechCommerce.Models;
using TechCommerce.Repositories;

namespace TechCommerce.Controllers
{
    public class CartController : Controller
    {
        private readonly IGenericRepository<Cart> CartRepository;
        private readonly ICartProductsRepository CartProductRepository;
        private readonly IGenericRepository<Product> ProductRepository;
        private readonly IGenericRepository<Customer> CustomerRepository;
        private readonly UserManager<Customer> UserManager;

        public CartController(IGenericRepository<Cart> CartRepository,
                                ICartProductsRepository CartProductRepository,
                                IGenericRepository<Product> ProductRepository,
                                IGenericRepository<Customer> CustomerRepository,
                                UserManager<Customer> UserManager)
        {
            this.CartRepository = CartRepository;
            this.CartProductRepository = CartProductRepository;
            this.ProductRepository = ProductRepository;
            this.UserManager = UserManager;
            this.CustomerRepository = CustomerRepository;
        }

        public async Task<IActionResult> Index()
        {
            var userId = UserManager.GetUserId(User);

            Customer user = CustomerRepository.GetById(userId);

            Cart mycart = CartRepository.GetById(user.CartId);

            ViewBag.CartTotalPrice = mycart.totalPrice;

            var cartProducts = await CartProductRepository.GetCartProductsAsync(user.CartId);

            return View(cartProducts);
        }

        [Authorize]
        public IActionResult AddToCart(int productId, int quantity = 1)
        {
            var userId = UserManager.GetUserId(User);

            Customer customer = CustomerRepository.GetById(userId);

            var product = ProductRepository.GetById(productId);

            var cartProduct = CartProductRepository.GetAll()
                .FirstOrDefault(cp => cp.CartId == customer.CartId && cp.ProductId == productId);

            if (cartProduct != null)
            {
                // If the product is already in the cart, increase the quantity
                cartProduct.Quantity += quantity;
                CartProductRepository.Update(cartProduct);
            }
            else
            {
                var newCartProduct = new CartProducts
                {
                    CartId = customer.CartId,
                    ProductId = product.Id,
                    Quantity = quantity
                };
                CartProductRepository.Add(newCartProduct);
            }

            Cart cart = CartRepository.GetById(customer.CartId);
            cart.totalPrice += product.Price * quantity;
            CartRepository.Update(cart);

            CartProductRepository.Save();

            return NoContent();
        }
        public IActionResult IncrementToCart(int productId)
        {
            var userId = UserManager.GetUserId(User);

            Customer customer = CustomerRepository.GetById(userId);

            var product = ProductRepository.GetById(productId);

            var cartProduct = CartProductRepository.GetAll()
                .FirstOrDefault(cp => cp.CartId == customer.CartId && cp.ProductId == productId);

            if (cartProduct != null)
            {
                // If the product is already in the cart, increase the quantity
                cartProduct.Quantity += 1;
                CartProductRepository.Update(cartProduct);
            }

            Cart cart = CartRepository.GetById(customer.CartId);
            cart.totalPrice += product.Price;
            CartRepository.Update(cart);

            CartProductRepository.Save();

            return NoContent();
        }

        public IActionResult DecrementToCart(int productId)
        {
            var userId = UserManager.GetUserId(User);

            Customer customer = CustomerRepository.GetById(userId);

            var product = ProductRepository.GetById(productId);

            var cartProduct = CartProductRepository.GetAll()
                .FirstOrDefault(cp => cp.CartId == customer.CartId && cp.ProductId == productId);

            if (cartProduct.Quantity > 1)
            {
                if (cartProduct != null)
                {
                    // If the product is already in the cart, increase the quantity
                    cartProduct.Quantity -= 1;
                    CartProductRepository.Update(cartProduct);
                }

                Cart cart = CartRepository.GetById(customer.CartId);
                cart.totalPrice -= product.Price;
                CartRepository.Update(cart);

                CartProductRepository.Save();
            }

            return NoContent();
        }

        public ActionResult RemoveFromCart(int productId)
        {
            var userId = UserManager.GetUserId(User);

            Customer customer = CustomerRepository.GetById(userId);

            var product = ProductRepository.GetById(productId);

            var cartProduct = CartProductRepository.GetAll()
                .FirstOrDefault(cp => cp.CartId == customer.CartId && cp.ProductId == productId);

            if (cartProduct != null)
            {
                CartProductRepository.RemoveProduct(cartProduct);
                CartProductRepository.Save();
            }

            Cart cart = CartRepository.GetById(customer.CartId);
            cart.totalPrice -= product.Price * cartProduct.Quantity;
            CartRepository.Update(cart);
            CartProductRepository.Save();

            return RedirectToAction("Index");
        }

    }
}

TechCommerce/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;
using System.Security.Claims;
using TechCommerce.Data;
using TechCommerce.Models;
using TechCommerce.Repositories;
using Address = TechCommerce.Models.Address;
using Customer = TechCommerce.Models.Customer;
using Product = TechCommerce.Models.Product;

namespace TechCommerce.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext Context;
        private readonly UserManager<Customer> Usrmanager;
        private readonly IGenericRepository<Order> OrderRepository;
        private readonly IGenericRepository<Product> ProductRepository;
        private readonly IGenericRepository<Cart> CartRepository;
        private readonly ICartProductsRepository CartProductsRepository;
        private readonly IOrderProductRepository OrderProductRepository;
        private readonly IGenericRepository<Customer> CustomerRepository;

        public OrderController(IGenericRepository<Order> OrderRepository, ApplicationDbContext context, 
                               UserManager<Customer> Usrmanager,
                               IGenericRepository<Cart> CartRepository,
                               IOrderProductRepository OrderProductRepository,
                               ICartProductsRepository CartProductsRepository,
                               IGenericRepository<Product> ProductRepository,
                               IGenericRepository<Customer> CustomerRepository)  //Inject
        {
            this.OrderRepository = OrderRepository;
            Context = context;
            this.Usrmanager = Usrmanager;
            this.CartRepository = CartRepository;
            this.OrderProductRepository = OrderProductRepository;
            this.CartProductsRepository = CartProductsRepository;
            this.ProductRepository = ProductRepository;
            this.CustomerRepository = CustomerRepository;
        }

        // Read
        public IActionResult Index(int pg = 1)
        {
            List<Order> orders;

            if (User.IsInRole("Admin"))
            {
                orders = OrderRepository.GetAll();
            }
            else
            {
                var customerId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                orders = OrderRepository.GetAll().Where(p => p.CustomerId == customerId).ToList();
            }

            const int pageSize = 8;
            if (pg < 1)
                pg = 1;

            var pager = new Pager(orders.Count, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            List<Order> filteredOrders = orders.Skip(recSkip).Take(pager.PageSize).ToList();

            OrdersPagertViewModel ordersPagertViewModel = new OrdersPagertViewModel()
            {
                orders = filteredOrders,
                Pager = pager,
            };

            return View("Index", ordersPagertViewModel);
        }

        public IActionResult ShowDetails(int id)
        {
            Order? order = OrderRepository.GetById(id);

            List<OrderDetailsViewModel> ordersList = OrderProductRepository.GetOrderDetails(order.Id);

            ViewBag.totalPrice = order.Price;
            return View("ShowDetails", ordersList);
        }

        // U
        public IActionResult Edit(int id)
        {
            Order? order = OrderRepository.GetById(id);

            if (order != null)
            {
                return View("Edit", order);
            }
            else
            {
                return NotFound();
            }
        }

        public ActionResult SaveEdit(Order order, int id)
        {
            Order? orderssDB = OrderRepository.GetById(id);

            if (orderssDB != null)
            {
                orderssDB.State = order.State;

                OrderRepository.Update(orderssDB);
                OrderRepository.Save();

                return RedirectToAction("Index");
            }

            return View("Edit", order);
        }

        // Delete
        public ActionResult Delete(int id)
        {
            Order? order = OrderRepository.GetById(id);

            OrderRepository.Delete(id);
            OrderRepository.Save();

            return RedirectToAction("Index");
        }
        [Authorize]
        public async Task<IActionResult> CheckOut() 
        {
            var userId = Usrmanager.GetUserId(User);

            Customer user = CustomerRepository.GetById(userId);
            
            List<Address> addresses = Context.Addresses?.Where(A => A.CustomerId == user.Id).ToList() ?? new List<Address>();

            return View(addresses);
        }
        public async Task<IActionResult> PlaceOrder(int id,String mainst,String City)
        {
           
            var userId = Usrmanager.GetUserId(User);

            Customer user = CustomerRepository.GetById(userId);

            Cart c = CartRepository.GetById(user.CartId);

            List<CartProducts> cartproducts = CartProductsRepository.GetCartProducts(user.CartId);

            Order newOrder = new Order()
            {
                Price = c.totalPrice,
                CustomerId = userId,
                State="Placed",
                Customer=user,
                Date=DateTime.Now,
                AddressId=id
                
            };
            OrderRepository.Add(newOrder);
            OrderRepository.Save();

            foreach(var item in cartproducts)
            {
                OrderProduct entry= new OrderProduct
                {
                    OrderId = newOrder.Id,
                    Order = newOrder,
                    ProductId = item.ProductId,
                    Product = item.Product,
                    Quantity = item.Quantity,
                    Price=item.Product.Price
                };
                OrderProductRepository.Add(entry);
                CartProductsRepository.RemoveProduct(item);
               
                // Update the units in the stock 
                Product productDb = ProductRepository.GetById(item.ProductId);
                productDb.Units -= item.Quantity;
                ProductRepository.Update(productDb);
                ProductRepository.Save();
            }
            c.totalPrice = 0;
            CartProductsRepository.Save();
            OrderProductRepository.Save();

            TempData["success"] = "Order Placed Successfully";
            ViewBag.address= $"{mainst} | {City}";
            return View(newOrder);
        }

        
        public ActionResult PaymentMethod(int id, String mainst, String City)
        {
            ViewBag.id = id;
            ViewBag.mainst= mainst;
            ViewBag.City= City;
            return View();
        }

        [HttpPost]
        public ActionResult PaymentMethod(int id, String mainst, String City, String paymentmethod)
        {
            
            if (paymentmethod == "Cash")
            {
                return RedirectToAction(nameof(PlaceOrder), new { id = id, mainst = mainst, city = City });
            }
            else
            {
                return RedirectToAction(nameof(CreateCheckoutSession), new { id = id, mainst = mainst, city = City });
              
            }
        }

       
        public async Task<IActionResult> CreateCheckoutSession(int id, String mainst, String City)
        {
            var domain = "http://localhost:27980/";
            var userId = Usrmanager.GetUserId(User);

            Customer user = CustomerRepository.GetById(userId);

            Cart c = CartRepository.GetById(user.CartId);

            List<CartProducts> cartproducts = CartProductsRepository.GetCartProducts(user.CartId);

            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>(),
                
                Mode = "payment",
                SuccessUrl =domain+ $"Order/PlaceOrder?id={id}&mainst={mainst}&City={City}",
                CancelUrl = domain + $"Order/CheckOut",
            };

            foreach(var item in cartproducts)
            {

                var sessionitem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(item.Product.Price * 100),
                        Currency = "usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Product.Name,
                        },
                    },
                    Quantity = item.Quantity,
                };
                options.LineItems.Add(sessionitem);
             
            }
            var service = new SessionService();
            Session session = service.Create(options);

            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }
    }
}

TechCommerce/Views/Cart/Index.cshtml
@model List<CartProductViewModel>

@{
    ViewData["Title"] = "My Cart";
}

<h1 class="pt-4 pb-3 cart-header">Your cart</h1>

@if (Model == null || !Model.Any())
{
    <p>Your cart is empty. Start adding products!</p>
}
else
{
    <div class="cart-container">
        <!-- Left side: Cart items -->
        <div class="cart-items">
            @foreach (var item in Model)
            {
                <div class="cart-item">
                    <div class="item-details my-2">
                        <div class="image-container">
                            <img src="@item.ImageUrl" alt="@item.Name" class="item-image" />
                        </div>
                        <div class="item-info">
                            <p class="mt-2">@item.Name</p>
                            @{
                                var totalProductPrice = item.Price * item.Quantity;
                            }
                            <div class="item-price">
                                $<span id="totalProductPrice_@item.ProductId">@totalProductPrice</span>
                            </div>
                        </div>
                    </div>
                    <div class="item-buttons">
                        <a asp-action="RemoveFromCart" asp-controller="Cart" asp-route-productId="@item.ProductId" class="remove-btn">
                            <i class="fa fa-trash"></i>
                        </a>
                        <div class="item-quantity">
                            <button class="btn btn-outline-secondary decrement-btn" data-product-id="@item.ProductId" data-stock-units="@item.Units">-</button>
                            <input type="text" id="quantity_@item.ProductId" value="@item.Quantity" class="form-control text-center" readonly style="max-width: 60px;">
                            <button class="btn btn-outline-secondary increment-btn" data-product-id="@item.ProductId" data-stock-units="@item.Units">+</button>
                        </div>
                    </div>
                </div>
            }
        </div>

        <!-- Right side: Order Summary -->
        <div class="order-summary">
            <h2>Order Summary</h2>
            <div class="d-flex justify-content-between">
                <p class="order-details-header">Subtotal </p>
                <p class="subtotal">$@((ViewBag.CartTotalPrice)?.ToString("F2") ?? "0.00")</p>
            </div>

            <div class="d-flex justify-content-between border-bottom border-1 pb-2">
                <p class="order-details-header">Delivery Fee </p>
                <p class="Fee">$15</p>
            </div>
            <div class="d-flex justify-content-between pt-2 pb-3 total-price">
                <p class="order-details-header">Total </p>
                <p id="totalPrice">$@((ViewBag.CartTotalPrice + 15)?.ToString("F2") ?? "0.00")</p>
            </div>

            <div class="d-flex flex-row align-items-stretch justify-content-between">
                <input type="text" placeholder="Add promo code" class="form-control promo-code" style="width: 65%;" />
                <button class="apply-btn btn btn-primary" style="width: 30%;">Apply</button>
            </div>

            <a id="checkoutButton" asp-action="checkOut" asp-controller="Order" class="checkout-btn btn btn-primary">Go to Checkout</a>
        </div>
    </div>
}

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            function updateCart(productId, quantity, price, stockUnits) {
                $("#quantity_" + productId).val(quantity);
                var totalProductPrice = (quantity * price).toFixed(2);
                $("#totalProductPrice_" + productId).text(totalProductPrice);
                updateTotalPrice();

                if (quantity > stockUnits) {
                    $("#stockWarning_" + productId).show();
                    disableCheckout();
                } else {
                    $("#stockWarning_" + productId).hide();
                    checkCheckoutButton();
                }
            }

            function updateTotalPrice() {
                let totalPrice = 0;

                $(".cart-item").each(function () {
                    const productPriceText = $(this).find('.item-price span').text();
                    const productPrice = parseFloat(productPriceText);

                    if (!isNaN(productPrice)) {
                        totalPrice += productPrice;
                    }
                });

                $("#totalPrice").text("$" + totalPrice.toFixed(2));
                $(".subtotal").text("$" + totalPrice.toFixed(2));

            }


            function disableCheckout() {
                $("#checkoutButton").addClass("disabled");
            }

            function checkCheckoutButton() {
                let warnings = $(".text-danger:visible").length;
                if (warnings === 0) {
                    $("#checkoutButton").removeClass("disabled");
                } else {
                    $("#checkoutButton").addClass("disabled");
                }
            }

            // Handle increment button click
            $(".increment-btn").click(function (e) {
                e.preventDefault();
                var productId = $(this).data("product-id");
                var stockUnits = $(this).data("stock-units");

                var quantityInput = $("#quantity_" + productId);
                var currentQuantity = parseInt(quantityInput.val());

                if (currentQuantity >= stockUnits) {
                    alert("You cannot add more than the available stock units.");
                } else {
                    $.ajax({
                        url: '/Cart/IncrementToCart',
                        type: 'POST',
                        data: { productId: productId },
                        success: function () {
                            var pricePerUnit = parseFloat($("#totalProductPrice_" + productId).text()) / currentQuantity;
                            updateCart(productId, currentQuantity + 1, pricePerUnit, stockUnits);
                            checkCheckoutButton();
                        }
                    });
                }
            });

            // Handle decrement button click
            $(".decrement-btn").click(function (e) {
                e.preventDefault();
                var productId = $(this).data("product-id");
                var stockUnits = $(this).data("stock-units");

                $.ajax({
                    url: '/Cart/DecrementToCart',
                    type: 'POST',
                    data: { productId: productId },
                    success: function () {
                        var quantityInput = $("#quantity_" + productId);
                        var currentQuantity = parseInt(quantityInput.val());
                        var pricePerUnit = parseFloat($("#totalProductPrice_" + productId).text()) / currentQuantity;

                        if (currentQuantity > 1) {
                            updateCart(productId, currentQuantity - 1, pricePerUnit, stockUnits);
                        } else {
                            updateCart(productId, 1, pricePerUnit, stockUnits);
                        }
                        checkCheckoutButton();
                    }
                });
            });

            $(".table-hover tbody tr").each(function () {
                var productId = $(this).find('.increment-btn').data('product-id');
                var stockUnits = $(this).find('.increment-btn').data('stock-units');
                var currentQuantity = parseInt($("#quantity_" + productId).val());

                if (currentQuantity > stockUnits) {
                    $("#stockWarning_" + productId).show();
                    disableCheckout();
                }
            });

            checkCheckoutButton();
        });

    </script>

    <style>
        .cart-header {
            font-size: 1.9rem;
            font-weight: 700
        }

        .cart-container {
            display: flex;
            justify-content: space-between;
            gap: 20px;
        }

        .cart-items {
            width: 60%;
            border: solid #E6E6E6 1px;
            border-radius: 10px
        }

        .cart-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 15px;
        }

        .cart-item:not(:last-child) {
            border-bottom: 1px solid #E6E6E6;
        }

        .item-details {
            display: flex;
            justify-content: space-between;
        }

        .image-container {
            display: flex;
            justify-content: center; 
            align-items: center; 
            height: 130px;
        }

        .item-image {
            width: 140px;
            margin: auto 0;
            margin-right: 20px;
        }

        .item-info{
            display: flex;
            justify-content: space-around;
            flex-direction: column;
        }

        .item-info p {
            margin: 0;
            font-size: 1.5rem;
            font-weight: 600;
        }

        .item-info .item-price {
            font-size: 1.3rem;
            font-weight: 700;
        }

        .item-buttons{
            display: flex;
            flex-direction: column;
            justify-content: space-around;
            height: 130px;
            align-items:end;
            margin-right: 20px;
        }

        .item-quantity {
            display: flex;
            align-items: center;
        }

        .quantity-input {
            width: 40px;
            text-align: center;
            margin: 0 5px;
        }

        .remove-btn {
            color: red;
            cursor: pointer;
            float: right;
        }

        .order-summary {
            width: 35%;
            height: fit-content;
            padding: 20px;
                border: 1px solid #E6E6E6;
            border-radius: 5px;
        }

        .order-summary h2 {
            font-size: 1.4rem;
            font-weight: 700;
            margin-bottom: 20px;
        }

        .order-summary p {
            font-size: 17px;
            margin: 10px 0;
        }

        .order-summary .order-details-header {
            color: #666666
        }

        .order-summary .subtotal {
            font-weight: 700;
        }

        .Fee {
            font-weight: 700;
        }

        .total-price .order-details-header {
            font-weight: 600;
            color: #000
        }

        .total-price #totalPrice {
            font-weight: 800;
            font-size: 19px
        }

        .promo-code {
            width: 100%;
            margin-bottom: 10px;
            border: 1px solid #ddd;
            border-radius: 30px;
            padding: 10px;
            padding-left: 25px;
                height: 100%
            }

        .apply-btn {
            width: 100%;
            background-color: #000;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            border-radius: 30px;
            padding: 10px;
            height: 100%
        }

        .checkout-btn {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #000;
            color: white;
            text-align: center;
            border-radius: 5px;
            text-decoration: none;
            margin-top: 10px;
            border-radius: 30px;
         }
    </style>
}